<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<?php if ($view == 'page/update') { ?>
		<link rel="stylesheet" href="/codemirror/css/codemirror.css">
		<link rel="stylesheet" href="/codemirror/theme/darcula.css">
		<style>
			#preview,
			.CodeMirror {
				width: 100%;
				height: 600px;
			}
		</style>
	<?php } ?>

	<title>Ellestmanuelle | Administration</title>
</head>

<body>
	<?php if (isset($_SESSION['success'])) {
		$success = $_SESSION['success'];
		unset($_SESSION['success']);
	?>
		<div class="card-body">
			<div class="alert alert-success"><i class="fa fa-thumbs-up"></i>
				<?php echo $success ?>
			</div>
		</div>
	<?php } ?>

	<?php if (isset($_SESSION['error'])) {
		$error = $_SESSION['error'];
		unset($_SESSION['error']);
	?>
		<div class="card-body">
			<div class="alert alert-danger"><i class="fa fa-exclamation-triangle"></i>
				<?php echo $error ?>
			</div>
		</div>
	<?php } ?>

	<?php require $content ?>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
	<?php if ($view == 'page/update') { ?>
		<script src="/codemirror/js/codemirror.js"></script>
		<script src="/codemirror/mode/xml/xml.js"></script>
		<script src="/codemirror/mode/javascript/javascript.js"></script>
		<script src="/codemirror/mode/css/css.js"></script>
		<script src="/codemirror/mode/htmlmixed/htmlmixed.js"></script>
		<script>
			var header = '<!DOCTYPE html>' + 
			'<html>' + 
			'<head>' + 
			'<meta charset="utf-8">' + 
			'<title>Test</title>' + 
			'<meta name="description" content="créations artistiques et artisanales / illustrations / interventions ateliers">' + 
			'<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">' + 
			'<link rel="stylesheet" type="text/css" href="fonts/material-design-iconic-font/css/material-design-iconic-font.min.css">' + 
			'<link rel="stylesheet" type="text/css" href="fonts/linearicons/style.css">' + 
			'<link rel="stylesheet" type="text/css" href="css/poppins-font.css">' + 
			'<link rel="stylesheet" type="text/css" href="fonts/Playlist/playlist-script-font.css">' + 
			'<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">' + 
			'<link rel="stylesheet" href="css/owl.carousel.min.css">' + 
			'<link rel="stylesheet" href="css/owl.theme.default.min.css">' + 
			'<link rel="stylesheet" href="css/animate.css">' + 
			'<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />' + 
			'<link rel="stylesheet" href="css/style.min.css" />' + 
			'</head>' + 
			'<body>';
			var footer = '<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></scr' + 'ipt>' +
			'<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></scr' + 'ipt>' + 
			'<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></scr' + 'ipt>' + 
			'<script src="js/owl.carousel.min.js"></scr' + 'ipt>' + 
			'<script src="js/OwlCarousel2Thumbs.min.js"></scr' + 'ipt>' + 
			'<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></scr' + 'ipt>' + 		
			'<script src="js/sweetalert.min.js"></scr' + 'ipt>' + 
			'<script src="js/config-contact.js"></scr' + 'ipt>' + 
			'<script src="js/custom.js"></scr' + 'ipt>' + 
			'</body>' + 
			'</html>';

			function updatePreview(content) {
				var previewFrame = document.getElementById('preview')
				var preview = previewFrame.contentDocument || previewFrame.contentWindow.document
				preview.open()
				preview.write(header + ' ' + content + ' ' + footer)
				preview.close()
			}

			var cm = CodeMirror.fromTextArea(document.getElementById('content'), {
				lineNumbers: true,
				lineWrapping: true,
				mode: "htmlmixed",
				theme: "darcula"
			}).on("change", function(cm, change) {
				updatePreview(cm.getValue())
			})

			updatePreview(document.getElementById('content').value)
		</script>
	<?php } ?>
</body>

</html>