<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<?php if ($view == 'page/update') { ?>
		<link rel="stylesheet" href="/codemirror/css/codemirror.css">
		<link rel="stylesheet" href="/codemirror/theme/darcula.css">
		<style>
			#preview,
			.CodeMirror {
				width: 100%;
				height: 600px;
			}
		</style>
	<?php } ?>

	<title>Ellestmanuelle | Administration</title>
</head>

<body>
	<?php if (isset($_SESSION['success'])) {
		$success = $_SESSION['success'];
		unset($_SESSION['success']);
	?>
		<div class="card-body">
			<div class="alert alert-success"><i class="fa fa-thumbs-up"></i>
				<?php echo $success ?>
			</div>
		</div>
	<?php } ?>

	<?php if (isset($_SESSION['error'])) {
		$error = $_SESSION['error'];
		unset($_SESSION['error']);
	?>
		<div class="card-body">
			<div class="alert alert-danger"><i class="fa fa-exclamation-triangle"></i>
				<?php echo $error ?>
			</div>
		</div>
	<?php } ?>

	<?php require $content ?>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
	<?php if ($view == 'page/update') { ?>
		<script src="/codemirror/js/codemirror.js"></script>
		<script src="/codemirror/mode/xml/xml.js"></script>
		<script src="/codemirror/mode/javascript/javascript.js"></script>
		<script src="/codemirror/mode/css/css.js"></script>
		<script src="/codemirror/mode/htmlmixed/htmlmixed.js"></script>
		<script>
			function updatePreview(content) {
				var previewFrame = document.getElementById('preview')
				var preview = previewFrame.contentDocument || previewFrame.contentWindow.document
				preview.open()
				preview.write(content)
				preview.close()
			}

			var cm = CodeMirror.fromTextArea(document.getElementById('content'), {
				lineNumbers: true,
				lineWrapping: true,
				mode: "htmlmixed",
				theme: "darcula"
			}).on("change", function(cm, change) {
				updatePreview(cm.getValue())
			})

			updatePreview(document.getElementById('content').value)
		</script>
	<?php } ?>
</body>

</html>