<div class="card">
	<div class="card-header">
		<i class="fa fa-fw fa-plus-circle"></i> <strong>Ajout</strong>
		<a href="/admin/documents" class="float-right btn btn-dark btn-sm"><i class="fa fa-arrow-circle-left"></i> Retour</a>
	</div>
	<div class="card-body">
		<div class="col-12">
			<form method="post" enctype="multipart/form-data">
				<div class="form-group">
					<label>Document <span class="text-danger">*</span></label>
					<br />
					<input type="file" class="tel form-control" name="document" id="document" required>
				</div>
				<div class="form-group">
					<button type="submit" name="submit" value="submit" id="submit" class="btn btn-primary"><i class="fa fa-fw fa-plus-circle"></i> Ajouter</button>
				</div>
			</form>
		</div>
	</div>
</div>