<div class="card">
	<div class="card-header">
		<i class="fa fa-fw fa-globe"></i><strong>Parcours des documents</strong>
		<a href="/admin" class="float-right btn btn-dark btn-sm"><i class="fa fa-arrow-circle-left"></i> Retour</a>
		<a href="/admin/document/add" class="float-right btn btn-success btn-sm"><i class="fa fa-fw fa-plus-circle"></i> Ajout</a>
	</div>
</div>

<div>
	<table class="table table-striped table-bordered">
		<thead>
			<tr class="bg-primary text-white">
				<th>Id</th>
				<th>Miniature</th>
				<th>Balise</th>
				<th class="text-center">Action</th>
			</tr>
		</thead>
		<tbody>
			<?php
			if (count($data) > 0) {
				foreach ($data as $document) {
			?>
					<tr>
						<td><?php echo $document['id']; ?></td>
						<?php
						$file_parts = pathinfo($document['name']);
						if (
							$file_parts['extension'] == "jpg" ||
							$file_parts['extension'] == "jpeg" ||
							$file_parts['extension'] == "png" ||
							$file_parts['extension'] == "gif"
						) {
						?>
							<td>
								<img src="/images/uploads/<?php echo $document['name']; ?>" class="img-thumbnail" width="200px" />
							</td>
							<td><?php echo "&lt;img src=\"/images/uploads/" . $document['name'] . "\" /&gt;"; ?></td>
						<?php
						} else {
						?>
							<td>
								<a href="/images/uploads/<?php echo $document['name']; ?>" target="_blank"><?php echo $document['name']; ?></a>
							</td>
							<td><?php echo "&lt;a href=\"/images/uploads/" . $document['name'] . "\" target=\"_blank\"&gt;" . $document['name'] . "&lt;/a&gt;"; ?></td>
						<?php
						}
						?>
						<td align="center">
							<a href="/admin/document/<?php echo $document['id']; ?>/delete" class="text-danger" onClick="return confirm('Êtes-vous sûr ?');"><i class="fa fa-fw fa-trash"></i> Suppression</a>
						</td>

					</tr>
				<?php
				}
			} else {
				?>
				<tr>
					<td colspan="6" align="center">Rien à afficher !</td>
				</tr>
			<?php } ?>
		</tbody>
	</table>
</div>