<div class="card">
	<div class="card-header">
		<i class="fa fa-fw fa-plus-circle"></i> <strong><?php echo $data['mode'] == 'EDIT' ? 'Edition' : 'Ajout' ?></strong>
		<a href="/admin/creations" class="float-right btn btn-dark btn-sm"><i class="fa fa-arrow-circle-left"></i> Retour</a>
	</div>
	<div class="card-body">
		<div class="col-12">
			<form method="post" enctype="multipart/form-data">
				<div class="form-group">
					<label>Nom <span class="text-danger">*</span></label>
					<input type="text" name="name" id="name" class="form-control" value="<?php echo $data['creation']['name']; ?>" required>
				</div>
				<div class="form-group">
					<label>Description <span class="text-danger">*</span></label>
					<input type="text" name="description" id="description" class="form-control" value="<?php echo $data['creation']['description']; ?>" required>
				</div>
				<div class="form-group">
					<label>Image <span class="text-danger">*</span></label>
					<br />
					<i>750px * 1030px</i>
					<?php
					if ($data['creation']['picture'] != "") {
					?>
						<br />
						<img src="/images/uploads/<?php echo $data['creation']['picture']; ?>" class="img-thumbnail" width="300px" />
					<?php
					}
					?>
					<input type="file" class="tel form-control" name="picture" id="picture" value="<?php echo $data['creation']['picture']; ?>">
				</div>
				<div class="form-group">
					<label>Seconde image</label>
					<br />
					<i>750px * 1030px</i>
					<?php
					if ($data['creation']['picture2'] != "") {
					?>
						<br />
						<img src="/images/uploads/<?php echo $data['creation']['picture2']; ?>" class="img-thumbnail" width="300px" />
					<?php
					}
					?>
					<input type="file" class="tel form-control" name="picture2" id="picture2" value="<?php echo $data['creation']['picture2']; ?>">
				</div>
				<div class="form-group">
					<label>Theme</label>
					<select id="theme" name="theme" class="form-control">
						<option></option>
						<?php
						foreach ($data['themes'] as $theme) {
						?>
							<option value="<?php echo $theme["id"] ?>" <?php echo count($data['currentTheme']) > 0 && $data['currentTheme'][0]['id_theme'] == $theme["id"] ? "selected" : "" ?>><?php echo $theme["name"] ?></option>
						<?php } ?>
					</select>
				</div>
				<div class="form-group">
					<label>Technique</label>
					<select id="technique" name="technique" class="form-control">
						<option></option>
						<?php
						foreach ($data['techniques'] as $technique) {
						?>
							<option value="<?php echo $technique["id"] ?>" <?php echo count($data['currentTechnique']) > 0 && $data['currentTechnique'][0]['id_technique'] == $technique["id"] ? "selected" : "" ?>><?php echo $technique["name"] ?></option>
						<?php } ?>
					</select>
				</div>
				<div class="form-group">
					<input type="hidden" name="editId" id="editId" value="<?php echo $data['creation']['id'] ?>">
					<button type="submit" name="submit" value="submit" id="submit" class="btn btn-primary">
						<?php if ($data['mode'] == 'EDIT') { ?>
							<i class="fa fa-fw fa-edit"></i> Mettre à jour
						<?php } else { ?>
							<i class="fa fa-fw fa-plus-circle"></i> Ajouter
						<?php } ?>
					</button>
				</div>
			</form>
		</div>
	</div>
</div>