<div class="card">
	<div class="card-header">
		<i class="fa fa-fw fa-globe"></i><strong>Liste des themes</strong>
		<a href="/admin" class="float-right btn btn-dark btn-sm"><i class="fa fa-arrow-circle-left"></i> Retour</a>
		<a href="/admin/theme/add" class="float-right btn btn-success btn-sm"><i class="fa fa-fw fa-plus-circle"></i> Ajout</a>
	</div>
</div>

<div>
	<table class="table table-striped table-bordered">
		<thead>
			<tr class="bg-primary text-white">
				<th>Id</th>
				<th>Position</th>
				<th>Nom</th>
				<th class="text-center">Action</th>
			</tr>
		</thead>
		<tbody>
			<?php
			if (count($data) > 0) {
				foreach ($data as $theme) {
			?>
					<tr>
						<td><?php echo $theme['id']; ?></td>
						<td><?php echo $theme['position']; ?></td>
						<td><?php echo $theme['name']; ?></td>
						<td align="center">
							<a href="/admin/theme/<?php echo $theme['id']; ?>/update" class="text-primary"><i class="fa fa-fw fa-edit"></i> Edition</a> |
							<a href="/admin/theme/<?php echo $theme['id']; ?>/delete" class="text-danger" onClick="return confirm('Êtes-vous sûr ?');"><i class="fa fa-fw fa-trash"></i> Suppression</a>
						</td>

					</tr>
				<?php
				}
			} else {
				?>
				<tr>
					<td colspan="6" align="center">Rien à afficher !</td>
				</tr>
			<?php } ?>
		</tbody>
	</table>
</div>