<div class="card">
    <div class="card-header">
        <i class="fa fa-fw fa-globe"></i><strong>Administration</strong>
		<a href="/admin/logout" class="float-right btn btn-dark btn-sm"><i class="fa fa-sign-out"></i> Déconnexion</a>
    </div>
    <a href="/admin/creations" class="btn btn-light">Gestion des creations</a>
    <a href="/admin/themes" class="btn btn-light">Gestion des themes</a>
    <a href="/admin/techniques" class="btn btn-light">Gestion des techniques</a>
    <a href="/admin/pages" class="btn btn-light">Gestion des pages</a>
    <a href="/admin/documents" class="btn btn-light">Gestion des documents</a>
</div>